name: MarketPlace
version: '1.0-SNAPSHOT'
main: net.marketplace.MarketPlace
description: Marketplace plugin
author: Amps
api-version: '1.20'
commands:
  marketplace:
    description: Opens the marketplace GUI
  sell:
    description: Initiates the selling process
  transactions:
    description: Views recent transactions
  wipedatabase:
    description: Administrative GUI Management
    usage: /wipedatabase
  reloadmarketplace:
    description: Reload the plugin configuration
    permission: marketplace.admin
    permission-message: "You don't have permission to use this command."
  blackmarket:
    description: Opens the Black Market GUI.
    permission: blackmarket.use
    permission-message: You do not have permission to use the Black Market.
  blackmarketsell:
    description: Sells an item in the Black Market.
    permission: blackmarket.sell
    permission-message: You do not have permission to sell in the Black Market.